<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Roti Tawar',
                'category' => 'Bread',
                'price' => 13000,
                'description' => 'Tekstur pori yang halus dan sangat lembut. Pilihan tepat untuk konsumsi harian keluarga, baik dipanggang maupun diolah menjadi sandwich.',
                'image' => 'products/Roti Tawar.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Abon',
                'category' => 'Bread',
                'price' => 6500,
                'description' => 'Roti premium dengan olesan krim spesial dan taburan abon sapi yang melimpah di seluruh permukaannya.',
                'image' => 'products/Roti Abon.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Pisang Keju',
                'category' => 'Bread',
                'price' => 5000,
                'description' => 'Menggunakan pisang pilihan yang sudah matang sempurna (karamelisasi alami), dipadukan dengan keju gurih.',
                'image' => 'products/Roti Pisang Keju.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Pisang Coklat',
                'category' => 'Chocolate',
                'price' => 5000,
                'description' => 'Menggunakan pisang pilihan yang sudah matang sempurna (karamelisasi alami), dipadukan dengan coklat berkualitas.',
                'image' => 'products/Roti Pisang Coklat.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Coklat Keju',
                'category' => 'Chocolate',
                'price' => 4500,
                'description' => 'Perpaduan harmonis antara manisnya coklat dan gurihnya keju dalam satu adonan roti yang empuk.',
                'image' => 'products/Roti Coklat Keju.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Toast',
                'category' => 'Bread',
                'price' => 3000,
                'description' => 'Roti toast yang dipanggang sempurna dengan tekstur renyah di luar dan lembut di dalam.',
                'image' => 'products/Toast.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Donat Meses',
                'category' => 'Pastry',
                'price' => 4000,
                'description' => 'Donat tipe empuk (bukan tipe kopong) dengan topping meses coklat butiran yang melimpah.',
                'image' => 'products/Donat Meses Keju.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Donat Keju',
                'category' => 'Pastry',
                'price' => 4000,
                'description' => 'Donat tipe empuk (bukan tipe kopong) dengan topping parutan keju yang tebal.',
                'image' => 'products/Donat Meses Keju.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roll Cake',
                'category' => 'Cakes',
                'price' => 35000,
                'description' => 'Bolu gulung dengan tekstur pori yang rapat namun tetap lembut, dengan isian krim yang pas dan tidak membuat enek.',
                'image' => 'products/Roll Cake.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Sosis',
                'category' => 'Bread',
                'price' => 6000,
                'description' => 'Menggunakan sosis daging pilihan yang dibalut adonan roti lembut, dilengkapi dengan sedikit saus untuk cita rasa gurih.',
                'image' => 'products/Roti Sosis.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Choco Boat',
                'category' => 'Chocolate',
                'price' => 4000,
                'description' => 'Desain roti kapal yang berisi limpahan topping coklat di bagian atasnya, memberikan rasa yang lebih puas.',
                'image' => 'products/Roti Choco_Cheese Boat.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Cheese Boat',
                'category' => 'Bread',
                'price' => 4000,
                'description' => 'Desain roti kapal yang berisi limpahan topping keju di bagian atasnya, memberikan rasa yang lebih puas.',
                'image' => 'products/Roti Choco_Cheese Boat.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Pizza',
                'category' => 'Bread',
                'price' => 6000,
                'description' => 'Versi mini dari pizza klasik dengan topping saus tomat, sosis, dan keju yang dipanggang hingga kecoklatan.',
                'image' => 'products/Roti Pizza.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Tawar Pandan',
                'category' => 'Bread',
                'price' => 14000,
                'description' => 'Menggunakan ekstrak pandan alami yang memberikan aroma harum khas dan warna hijau lembut pada setiap helai roti.',
                'image' => 'products/Roti Tawar Pandan.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Kopi',
                'category' => 'Bread',
                'price' => 6500,
                'description' => 'Roti dengan lapisan luar (topping) aroma kopi yang renyah dan bagian dalam yang lembut.',
                'image' => 'products/Roti Kopi.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Blueberry Cup',
                'category' => 'Pastry',
                'price' => 4000,
                'description' => 'Perpaduan unik kesegaran selai blueberry dengan gurihnya keju, menciptakan rasa asam-manis-gurih yang seimbang.',
                'image' => 'products/Blueberry Cup.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Chiffon Cake Big',
                'category' => 'Cakes',
                'price' => 30000,
                'description' => 'Kue dengan tekstur yang sangat ringan, elastis, dan halus seperti kapas. Tersedia dalam ukuran besar.',
                'image' => 'products/Chiffon Cake Besar.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Kelapa',
                'category' => 'Bread',
                'price' => 4000,
                'description' => 'Varian favorit sepanjang masa dengan isian kelapa yang padat dan melimpah di setiap gigitan.',
                'image' => 'products/Roti Kelapa.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Blueberry Cheese',
                'category' => 'Pastry',
                'price' => 4000,
                'description' => 'Perpaduan unik kesegaran selai blueberry dengan gurihnya keju, menciptakan rasa asam-manis-gurih yang seimbang.',
                'image' => 'products/Blueberry Cheese.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Kering (Bagelan Manis)',
                'category' => 'Bread',
                'price' => 13000,
                'description' => 'Roti yang dipanggang kembali hingga renyah sempurna dengan olesan mentega dan gula. Camilan awet yang cocok menemani waktu minum teh.',
                'image' => 'products/Roti Kering (Bagelan Manis).jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Isi Keju',
                'category' => 'Bread',
                'price' => 3500,
                'description' => 'Varian favorit sepanjang masa dengan isian keju yang gurih dan melimpah di setiap gigitan.',
                'image' => 'products/Roti Isi Keju.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Vla Vanilla',
                'category' => 'Pastry',
                'price' => 4000,
                'description' => 'Tekstur roti lembut dengan isian vla vanilla yang creamy, dingin, dan tingkat manis yang pas.',
                'image' => 'products/Roti Vla Vanilla.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Semir Original',
                'category' => 'Pastry',
                'price' => 3000,
                'description' => 'Roti klasik dengan olesan buttercream spesial yang ringan dan tidak menempel di langit-langit mulut. Tersedia dengan topping meses coklat atau aroma moka yang kuat.',
                'image' => 'products/Roti Semir.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Semir Meses',
                'category' => 'Chocolate',
                'price' => 3500,
                'description' => 'Roti klasik dengan olesan buttercream spesial yang ringan dan tidak menempel di langit-langit mulut. Tersedia dengan topping meses coklat atau aroma moka yang kuat.',
                'image' => 'products/Roti Semir.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Semir Moca',
                'category' => 'Pastry',
                'price' => 3500,
                'description' => 'Roti klasik dengan olesan buttercream spesial yang ringan dan tidak menempel di langit-langit mulut. Tersedia dengan topping meses coklat atau aroma moka yang kuat.',
                'image' => 'products/Roti Semir.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Semir Moca Meses',
                'category' => 'Chocolate',
                'price' => 4000,
                'description' => 'Roti klasik dengan olesan buttercream spesial yang ringan dan tidak menempel di langit-langit mulut. Tersedia dengan topping meses coklat atau aroma moka yang kuat.',
                'image' => 'products/Roti Semir.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Isi Coklat',
                'category' => 'Chocolate',
                'price' => 4000,
                'description' => 'Varian favorit sepanjang masa dengan isian coklat yang lembut dan melimpah di setiap gigitan.',
                'image' => 'products/Roti Isi Coklat.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Chiffon Cake Small',
                'category' => 'Cakes',
                'price' => 25000,
                'description' => 'Kue dengan tekstur yang sangat ringan, elastis, dan halus seperti kapas. Tersedia dalam ukuran kecil.',
                'image' => 'products/Chiffon Cake Small.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Kerumpul Polos',
                'category' => 'Assorted',
                'price' => 9000,
                'description' => 'Roti loyang yang terdiri dari beberapa bagian kecil. Varian Premium menggunakan bahan dasar mentega lebih tinggi untuk kelembutan yang lebih tahan lama.',
                'image' => 'products/Kerumpul Polos.png',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Kerumpul Kombinasi Ekonomis',
                'category' => 'Assorted',
                'price' => 12000,
                'description' => 'Roti loyang yang terdiri dari beberapa bagian kecil. Varian Premium menggunakan bahan dasar mentega lebih tinggi untuk kelembutan yang lebih tahan lama.',
                'image' => 'products/Kerumpul Kombinasi.png',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Kerumpul Kombinasi Premium',
                'category' => 'Assorted',
                'price' => 13500,
                'description' => 'Roti loyang yang terdiri dari beberapa bagian kecil. Varian Premium menggunakan bahan dasar mentega lebih tinggi untuk kelembutan yang lebih tahan lama.',
                'image' => 'products/Kerumpul Kombinasi.png',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Kerumpul Coklat Ekonomis',
                'category' => 'Assorted',
                'price' => 13500,
                'description' => 'Roti loyang yang terdiri dari beberapa bagian kecil. Varian Premium menggunakan bahan dasar mentega lebih tinggi untuk kelembutan yang lebih tahan lama.',
                'image' => 'products/Kerumpul Coklat Premium.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Kerumpul Coklat Premium',
                'category' => 'Assorted',
                'price' => 15000,
                'description' => 'Roti loyang yang terdiri dari beberapa bagian kecil. Varian Premium menggunakan bahan dasar mentega lebih tinggi untuk kelembutan yang lebih tahan lama.',
                'image' => 'products/Kerumpul Coklat Premium.jpg',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Sobek Coklat',
                'category' => 'Assorted',
                'price' => 16000,
                'description' => 'Roti yang mudah dibagi (sobek) dengan isian coklat di setiap bagiannya. Cocok untuk sarapan bersama.',
                'image' => 'products/Roti Sobek Coklat.png',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Roti Sobek Coklat Keju',
                'category' => 'Assorted',
                'price' => 17000,
                'description' => 'Roti yang mudah dibagi (sobek) dengan isian coklat dan kombinasi keju di setiap bagiannya. Cocok untuk sarapan bersama.',
                'image' => 'products/Roti Sobek Coklat Keju.png',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Chiffon Slice',
                'category' => 'Cakes',
                'price' => 2500,
                'description' => 'Kue dengan tekstur yang sangat ringan, elastis, dan halus seperti kapas. Tersedia dalam ukuran potongan (slice).',
                'image' => 'products/Chiffon Slice.png',
                'status' => 'Tersedia',
            ],
            [
                'name' => 'Kue Mandarin',
                'category' => 'Cakes',
                'price' => 48000,
                'description' => 'Kue lapis mandarin dengan cita rasa khas yang lembut dan manis. Cocok untuk acara spesial dan oleh-oleh.',
                'image' => 'products/Kue Lapis Mandarin.png',
                'status' => 'Tersedia',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['name' => $product['name']],
                array_merge([
                    'image_2' => null,
                    'image_3' => null,
                ], $product)
            );
        }
    }
}
